//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _450Orders
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int OrdersID { get; set; }
        public int StoreNumberID { get; set; }
        public int SalesPersonID { get; set; }
        public int CdID { get; set; }
        public int Price { get; set; }
        public System.DateTime Datetime { get; set; }
    }
}
